var registry = {
    Patient:
    [
        {
            property:"id",
            indexedProperty:"_id",
            type:"string",
            index:"id"
        },{
            property:"lastUpdated",
            indexedProperty:"_lastUpdated",
            type:"datetime",
            index:"datetime"
        },
        {
            property:"city",
            indexedProperty:"address-city",
            type:"string",
            index:"string"
        },
        {
            property:"district",
            indexedProperty:"address-state",
            type:"string",
            index:"string"
        },
        {
            property:"postalCode",
            indexedProperty:"address-postalcode",
            type:"string",
            index:"string"
        },
        {
            property:"name",
            type:"name",
            index:"string"
        },        
        {
            property:"identifier",
            indexedProperty:"identifier",
            type:"token",
            index:"token"
        },
        {
            property:"tag",
            indexedProperty:"_tag",
            type:"token",
            index:"token"
        },
        {
            property:"gender",
            type:"string",
            index:"string"
        },
        {
            property:"birthDate",
            type:"datetime",
            index:"datetime"
        },
        {
            property:"managingOrganization",
            type:"reference",
            index:"reference"
        },
        {
            property:"generalPractitioner",
            type:"reference",
            index:"reference"
        }
    ],
    Subscription:
    [
        {
            property:"id",
            indexedProperty:"_id",
            type:"string",
            index:"id"
        },
        {
            property:"lastUpdated",
            indexedProperty:"_lastUpdated",
            type:"datetime",
            index:"datetime"
        },
        {
            property:"tag",
            indexedProperty:"_tag",
            type:"token",
            index:"token"
        }, 
        {
            property:"status",
            type:"string",
            index:"string"
        },
        {
            property:"payload",
            type:"string",
            index:"string"
        },
        {
            property:"type",
            type:"string",
            index:"string"
        },
        {
            property:"endpoint",
            indexedProperty:"url",
            type:"uri",
            index:"uri"
        }
    ]
};

module.exports = {
    registry
}