//Change to fit capability format and call resources.js
var resources = {
    Subscription: 
    {
        searchParameters:
        [
            {
                name:"_id",
                modifiers:[],
                type:"id",
                path:"id"
            }, 
            {
                name:"_lastUpdated",
                modifiers:[],
                type:"dt",
                path:"meta.lastUpdated"
            }, 
            {
                name:"_tag",
                modifiers:[],
                type:"token",
                path:"meta.tag"
            },
            {
                name:"_profile",
                modifiers:[],
                type:"token",
                path:"meta.profile"
            },
            {
                name:"contact",
                modifiers:[],
                type:"token",
                path:"contact"
            },
            {
                name:"criteria",
                modifiers:["contains","exact"],
                type:"string",
                path:"criteria"
            },
            {
                name:"payload",
                modifiers:[],
                type:"token",
                path:"channel.payload"
            },
            {
                name:"status",
                modifiers:[],
                type:"code",
                path:"status"
            },
            {
                name:"type",
                modifiers:[],
                type:"token",
                path:"channel.type"
            },
            {
                name:"url",
                modifiers:[],
                type:"uri",
                path:"channel.endpoint"
            }
        ]
    },
    Patient:
    {
        searchParameters:[
            {
                name:"_id",
                modifiers:[],
                type:"id",
                path:"id"
            }, 
            {
                name:"_lastUpdated",
                modifiers:[],
                type:"dt",
                path:"meta.lastUpdated"
            }, 
            {
                name:"_tag",
                modifiers:[],
                type:"token",
                path:"meta.tag"
            },
            {
                name:"_profile",
                modifiers:[],
                type:"token",
                path:"meta.profile"
            },
            {
                name:"address-postcode",
                modifiers:["contains","exact"],
                type:"string",
                path:"address.postalCode"
            },
            {
                name:"birthdate",
                modifiers:[],
                type:"datetime",
                path:"birthDate"
            },
            {
                name:"gender",
                modifiers:["contains","exact"],
                type:"string",
                path:"gender"
            },
            {
                name:"family",
                modifiers:["contains","exact"],
                type:"string",
                path:"name.family"
            },
            {
                name:"given",
                modifiers:["contains","exact"],
                type:"string",
                path:"name.given"
            }, 
            {
                name:"identifier",
                modifiers:[],
                type:"token",
                path:"identifier"
            }, 
            {
                name:"name",
                modifiers:["contains","exact"],
                type:"string",
                path:"text"
            },
        ]
    } 

};

module.exports = {
    resources
}